### ISSUE TITLE
build error on master

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-grid#237]
On my Ubuntu 16.04 laptop, I get the following build error:

```
and@singularius:~/src/opm-grid|master > make
[  5%] Patching Makefile to be DUNE compatible
[  5%] Built target dune-compat
[ 10%] Updating version information
[ 10%] Built target update-version
[ 15%] Building CXX object CMakeFiles/opmgrid.dir/dune/grid/cpgrid/CpGrid.cpp.o
/home/and/src/opm-grid/dune/grid/cpgrid/CpGrid.cpp: In member function ‘std::pair<bool, std::unordered_set<std::__cxx11::basic_string<char> > > Dune::CpGrid::scatterGrid(Opm::EclipseStateConstPtr, const double*, int)’:
/home/and/src/opm-grid/dune/grid/cpgrid/CpGrid.cpp:129:40: error: ‘part_and_wells’ was not declared in this scope
     return std::make_pair(true, get<1>(part_and_wells));
                                        ^
CMakeFiles/opmgrid.dir/build.make:110: recipe for target 'CMakeFiles/opmgrid.dir/dune/grid/cpgrid/CpGrid.cpp.o' failed
```

I've updated to the latest master branches of all OPM modules as well as and ERT and I'm using the dune packages shipped with Ubuntu. Also, I've build from scratch, i.e., this should not be caused by any artifacts of previous builds. can anybody reproduce this?

**Comment by andlaus** [comment]
note: this seems to be caused by the merge of #232. (without it, it builds.)

**Comment by blattms** [comment]
Seems to be a duplicate of #235. Please close if you agree.
