### ISSUE TITLE
How to run this module?

### ISSUE THREAD

**Issue by liuhao-7657** [OPM/opm-grid#470]
I have downloaded opm-grid, but i don't know how to run it. I'm confused, could you please give me some suggestion? 

I try to run a test ,it shows that: 

test_cartgrid.cpp:21:10: fatal error: config.h: No such file or directory
 #include "config.h"
          ^~~~~~~~~~
compilation terminated.

**Comment by atgeirr** [comment]
The module is part of the larger OPM set of modules, and cannot be compiled in isolation, since it depends on the module opm-common. You can find build instructions for compiling OPM from source here:

https://opm-project.org/?page_id=231

The particular compile error you see is because you do not have a config.h file. This file will be automatically generated for you when you run cmake, as described on the linked page. I close this issue as resolved, feel free to reopen it or make a new issue if there are problems ior issues with the build instructions linked.
